export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const UPDATE_CUISINE = "UPDATE_FOOD_TYPE";
export const UPDATE_OPTION = "UPDATE_OPTION";
export const UPDATE_RESTAURANT = "UPDATE_RESTAURANT";
export const UPDATE_RESTAURANTS = "UPDATE_RESTAURANTS";
